&lt;?php foreach($articles as $article): ?&gt;   
    &lt;div class&#x3D;&quot;news-spacing&quot;&gt;
        &lt;a class&#x3D;&quot;news-article theme-&lt;?&#x3D; $article[&quot;color&quot;] ?&gt;&quot; href&#x3D;&quot;#&quot;&gt;
            &lt;span class&#x3D;&quot;news-link theme&quot;&gt;&lt;?&#x3D; $article[&quot;type&quot;] ?&gt;&lt;&#x2F;span&gt;
            &lt;div class&#x3D;&quot;aspect-container&quot;&gt;
                &lt;img src&#x3D;&quot;img&#x2F;news-articles&#x2F;&lt;?&#x3D; $article[&quot;image_url&quot;] ?&gt;&quot; alt&#x3D;&quot;News Thumbnail&quot; class&#x3D;&quot;news-thumbnail&quot;&gt;
            &lt;&#x2F;div&gt;
            &lt;div class&#x3D;&quot;news-details&quot;&gt;
                &lt;h3&gt;&lt;?&#x3D; truncate($article[&quot;title&quot;], 50) ?&gt;&lt;&#x2F;h3&gt;
                &lt;p class&#x3D;&quot;text-small&quot;&gt;&lt;?&#x3D; truncate($article[&quot;description&quot;], 100) ?&gt;&lt;&#x2F;p&gt;
                &lt;div class&#x3D;&quot;read-more-btn theme-btn&quot;&gt;Read More&lt;&#x2F;div&gt;
                &lt;hr&gt;
                &lt;div class&#x3D;&quot;posted-by&quot;&gt;
                    &lt;img src&#x3D;&quot;img&#x2F;logo&#x2F;&lt;?&#x3D; $article[&quot;author_picture&quot;] ?&gt;&quot; alt&#x3D;&quot;Profile Picture&quot; class&#x3D;&quot;posted-by--logo-img&quot;&gt;
                    &lt;div class&#x3D;&quot;news-author&quot;&gt;
                        &lt;p&gt;&lt;strong&gt;Posted by &lt;?&#x3D; $article[&quot;author_name&quot;] ?&gt;&lt;&#x2F;strong&gt;&lt;&#x2F;p&gt;
                        &lt;p class&#x3D;&quot;text-small&quot;&gt;&lt;?php $date &#x3D; new DateTime($article[&quot;posted_at&quot;]); echo $date-&gt;format(&quot;jS F Y&quot;); ?&gt;&lt;&#x2F;p&gt;
                    &lt;&#x2F;div&gt;
                &lt;&#x2F;div&gt;
            &lt;&#x2F;div&gt;
        &lt;&#x2F;a&gt;
    &lt;&#x2F;div&gt;
&lt;?php endforeach; ?&gt;